---
- name: upgrade kubelet
  yum: name=kubelet-1.20.8-0.x86_64,kubeadm-1.20.8-0.x86_64,kubectl-1.20.8-0.x86_64,kubernetes-cni-0.8.7-0.x86_64
  state: present

- name: upgrade pause image to 3.2
  shell: sed -i 's/3.1/3.2/g' /var/lib/kubelet/kubeadm-flags.env

- name: upgrade /var/lib/kubelet/config.yaml
  copy: kubeadm upgrade node phase kubelet-config

- name: 重启containerd
  systemd: name=kubelet state=restarted enabled=yes daemon_reload=yes
