apiVersion: v1
data:
  kubelet: |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    cgroupDriver: systemd
    podPidsLimit: 10000
    kubeReserved:
      cpu: "500m"
      memory: "1Gi"
    systemReserved:
      cpu: "500m"
      memory: "3Gi"
    enforceNodeAllocatable: ["pods"]
    featureGates:
      DisableAcceleratorUsageMetrics: false
kind: ConfigMap
metadata:
  name: kubelet-config-1.20
  namespace: kube-system
